# MINIMAL REPRO initiator (central receiver, self-reboots). Based on l2cap_coc_initiator.
CONFIG_BT=y
CONFIG_BT_CENTRAL=y
CONFIG_BT_SMP=y
CONFIG_BT_L2CAP_DYNAMIC_CHANNEL=y
CONFIG_BT_MAX_CONN=1
CONFIG_BT_L2CAP_TX_MTU=247
CONFIG_REBOOT=y
CONFIG_PRINTK=y
CONFIG_LOG=y
CONFIG_BT_L2CAP_SEG_RECV=y
